---
name: Checkov
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: kubernetes
          framework: kubernetes 
          # Setting a SARIF output will generate a file named "results.sarif" containing your test results
          # args: "-o sarif"
          output_file_path: ./results.sarif
      - name: Expose report
        uses: actions/upload-artifact@v2
        with:
          name: SARIF results
          path: ./results.sarif
      # Uploads results.sarif to GitHub repository using the upload-sarif action
      - name: Upload result to GitHub Code Scanning      
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ./results.sarif