---
name: Checkov
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkov:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write    
    steps:
      - uses: actions/checkout@v3
      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: kubernetes
          framework: kubernetes 
          # output_file_path: ./results.sarif
      - name: Expose report
        uses: actions/upload-artifact@v3
        with:
          name: SARIF results
          path: results.sarif
      # Uploads results.sarif to GitHub repository using the upload-sarif action
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif